import { ArrowUpRight } from 'lucide-react'
import { AKSOSLogo, ATISLogo } from '@/components/brand'
import { InterestForm } from '@/components/interest-form'
import { AtisRevelation, ClosingEntry, HeroField, HorizonTrajectories, ParticipationField, PerspectiveLens, ProvenanceTrace, RitaConvergence, ZimbabweCaseStudy } from '@/components/visuals'

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span className="eyebrow-rule" />{children}</p> }
function Header() { return <header className="site-header"><a href="#top" aria-label="AKSOS home"><AKSOSLogo compact /></a><nav aria-label="Primary navigation"><a href="#problem">Problem</a><a href="#atis">ATIS</a><a href="#rita">RITA</a><a href="#participate">Participate</a></nav><a className="header-link" href="#participate">Get involved <ArrowUpRight size={14} /></a></header> }
function Section({ id, eyebrow, title, children, className = '' }: { id?: string; eyebrow: string; title: React.ReactNode; children: React.ReactNode; className?: string }) { return <section id={id} className={`section split ${className}`}><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div><div className="prose">{children}</div></section> }

export default function Page() { return <main id="top"><Header />
  <section className="hero section-grid"><div className="hero-copy"><Eyebrow>AKSOS // ECOSYSTEM VISIBILITY</Eyebrow><h1>Make the invisible <em>legible.</em></h1><p className="lede">Complexity contains structure. Structure creates context. Context creates relevance. AKSOS explores how relevance can become actionable understanding.</p><a className="text-link" href="#problem">Explore the work →</a></div><HeroField /></section>
  <Section id="problem" eyebrow="01 // The visibility problem" title="Information is everywhere. Context is harder to find."><p>A government announcement may affect a project. A policy may change an industry. A company may depend on an institution. A report may contain a fact that only becomes meaningful when connected to something else.</p><p>AKSOS is exploring whether making these relationships visible can make an ecosystem easier to understand and participate in.</p><p className="statement">The ecosystem already exists. The challenge is making its structure visible enough to understand.</p></Section>
  <Section eyebrow="02 // The hypothesis" title="Visibility may be infrastructure."><p>This is not a proven claim. It is a question worth testing in a real environment, with intellectual honesty and inspectable evidence.</p><div className="flow">VISIBILITY<br />↓<br />STRUCTURE<br />↓<br />UNDERSTANDING<br />↓<br />PARTICIPATION</div></Section>
  <Section eyebrow="03 // From idea to experiment" title="A hypothesis needs something real to test it against."><p>Zimbabwe is the first environment in which we are exploring the question in practice. Not because one country represents a continent, but because a real ecosystem provides what an abstract model cannot.</p><ZimbabweCaseStudy /></Section>
  <section id="atis" className="section"><div className="section-heading"><div><Eyebrow>04 // ATIS</Eyebrow><h2><ATISLogo /> Information becoming intelligence.</h2></div><p className="section-intro">ATIS is not simply information → AI → answer. One underlying material gains structure, context and meaning.</p></div><AtisRevelation /></section>
  <section id="rita" className="section"><div className="section-heading"><div><Eyebrow>05 // RITA</Eyebrow><h2>Not every connection is a story.</h2></div><p className="section-intro">Relationships are easy to collect. Meaning is harder to see.</p></div><div className="rita-grid"><RitaConvergence /><div className="prose"><p>RITA examines candidate relationships, identifies patterns and helps form coherent stories from underlying evidence.</p><p className="statement">CONNECTION ≠ COHERENCE<br />COHERENCE → STORY</p></div></div></section>
  <Section eyebrow="06 // Provenance" title="Intelligence should be inspectable."><p>If a conclusion depends on a relationship, inspect the relationship. If it depends on a fact, inspect the fact. If the fact comes from evidence, identify the source.</p><ProvenanceTrace /></Section>
  <Section eyebrow="07 // Perspective" title="The same ecosystem can mean different things from different positions."><p>The environment remains stable. Changing perspective changes emphasis, hierarchy and contextual significance.</p><PerspectiveLens /></Section>
  <Section eyebrow="08 // Participation" title="Participation is a pathway, not a database record."><p>Actors begin at the edge, bring context, ask questions and enter the shared field at the depth appropriate to them.</p><ParticipationField /></Section>
  <Section eyebrow="09 // Horizon" title="Several trajectories may emerge from present conditions."><p>AKSOS does not claim to predict the future. It makes possible trajectories easier to examine without pretending that uncertainty has disappeared.</p><HorizonTrajectories /></Section>
  <section id="participate" className="section form-section"><div className="center-copy"><Eyebrow>10 // Choose an entry point</Eyebrow><h2>What do you want to do with what you have seen?</h2><p>Explore, investigate or participate. Tell us what brought you here and where you see yourself engaging with the work.</p></div><ClosingEntry /><div id="interest-form"><InterestForm contactEmail={process.env.CONTACT_EMAIL ?? 'connect@atis.net'} /></div></section>
  <footer><AKSOSLogo /><span>Exploring ecosystem visibility, intelligence and participation.</span><a href="mailto:connect@atis.net">connect@atis.net</a></footer>
</main> }
