import { ArrowUpRight } from 'lucide-react'
import { AKSOSLogo, ATISLogo } from '@/components/brand'
import { EcosystemCanvas, PerspectiveSection, RitaSequencer } from '@/components/aksos-graphs'
import { InterestForm } from '@/components/interest-form'

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span className="eyebrow-rule" />{children}</p> }
function Header() { return <header className="site-header"><a href="#top" aria-label="AKSOS home"><AKSOSLogo compact /></a><nav className="nav" aria-label="Primary navigation"><a href="#problem">Problem</a><a href="#atis">ATIS</a><a href="#rita">RITA</a><a href="#perspective">Perspective</a><a href="#participate">Participate</a></nav><a className="header-link" href="#participate">Get involved <ArrowUpRight size={14} /></a></header> }
function Flow({ items }: { items: string[] }) { return <div className="flow">{items.map((item, index) => <span key={item}><b>{item}</b>{index < items.length - 1 && <i>↓</i>}</span>)}</div> }

export default function Page() { return <main id="top"><Header />
  <section className="hero section-grid"><div className="hero-copy"><Eyebrow>AKSOS // ECOSYSTEM VISIBILITY</Eyebrow><h1>Make the invisible <em>legible.</em></h1><p className="lede">Across every economy, people, enterprises, institutions, capital, projects, policies, markets and ideas move around one another. The information exists. What is harder to see is how those things relate.</p><a className="text-link" href="#work">Explore the work →</a><div className="hero-meta"><span>YOU → AKSOS → INTELLIGENCE → OPPORTUNITY → ACTION</span></div></div><EcosystemCanvas mode="ecosystem" /></section>
  <section id="problem" className="section split"><div><Eyebrow>01 // The problem</Eyebrow><h2>Information is everywhere. Context is harder to find.</h2></div><div className="prose"><p>A government announcement may affect a project. A policy may change an industry. A company may depend on an institution. A report may contain a fact that only becomes meaningful when connected to something else.</p><p>These relationships are scattered across sources, organisations and places. The challenge is understanding what is connected to what, why the connection matters, and what it means from your position.</p><p className="statement">If an ecosystem is difficult to see, it becomes difficult to understand.</p></div></section>
  <section className="section visual-section"><div className="section-heading"><div><Eyebrow>02 // The perspective</Eyebrow><h2>The same ecosystem can mean different things to different people.</h2></div><p className="section-intro">The ecosystem does not change. The question you ask of it does.</p></div><PerspectiveSection /></section>
  <section className="section split"><div><Eyebrow>03 // The hypothesis</Eyebrow><h2>What if visibility itself is infrastructure?</h2></div><div className="prose"><p>AKSOS began with a simple hypothesis: if an ecosystem becomes easier to see, it may become easier to understand and participate in.</p><p>This is not a claim that the problem has been solved. It is a question worth testing.</p><Flow items={['VISIBILITY', 'UNDERSTANDING', 'PARTICIPATION']} /></div></section>
  <section id="work" className="section split"><div><Eyebrow>04 // Origin</Eyebrow><h2>The idea came from trying to understand complex systems.</h2></div><div className="prose"><p>At CIVA, the work involved breaking down complex systems and examining how different parts interacted. Later experiences across countries exposed another side of the problem: important information could exist while understanding the environment required piecing together fragments.</p><p className="statement">Experience → Observation → Problem → Hypothesis → Experiment</p></div></section>
  <section className="section dark-band"><div className="band-grid"><div><Eyebrow>05 // From idea to experiment</Eyebrow><h2>A hypothesis needs something real to test it against.</h2></div><div className="prose"><p>Zimbabwe is the first environment in which we are exploring the question in practice. Not because one country represents a continent, but because a real ecosystem provides what an abstract model cannot: an opportunity to test the idea against reality.</p><Flow items={['HYPOTHESIS', 'ZIMBABWE', 'TEST', 'OBSERVE', 'LEARN', 'EVALUATE']} /></div></div></section>
  <section id="atis" className="section"><div className="section-heading"><div><Eyebrow>06 // ATIS</Eyebrow><h2><ATISLogo /> is an attempt to make ecosystem context understandable.</h2></div><p className="section-intro">Africa Trade Intelligence System is the intelligence system being developed through the AKSOS work.</p></div><div className="atis-grid"><EcosystemCanvas mode="atis" /><div className="prose"><p>Its purpose is not simply to collect information. A document may contain a fact; a fact may relate to an entity; that entity may connect to another entity through a policy, project, investment, institution or event.</p><Flow items={['INFORMATION', 'EVIDENCE', 'FACTS', 'ENTITIES', 'RELATIONSHIPS', 'CONTEXT', 'INTELLIGENCE']} /><p className="statement">The objective is not to produce more information. It is to make existing information more meaningful.</p></div></div></section>
  <section className="section split"><div><Eyebrow>07 // The intelligence model</Eyebrow><h2>Context changes the meaning of information.</h2></div><div className="prose"><p>A development in Zambia may have implications for Zimbabwe. The relevant question is not simply what opportunity exists in Zambia, but what could this mean for Zimbabwe, and what should a Zimbabwean actor understand about it?</p><p className="statement">The same evidence can produce a different understanding depending on where you stand.</p></div></section>
  <section className="section split"><div><Eyebrow>08 // What ATIS is not</Eyebrow><h2>Intelligence should be inspectable.</h2></div><div className="prose"><p>ATIS is not intended to replace judgement. If a conclusion depends on a relationship, the relationship should be traceable. If it depends on a fact, the fact should be traceable. If the fact comes from evidence, the source should be identifiable.</p><Flow items={['STORY', 'RELATIONSHIP', 'FACT', 'SOURCE']} /></div></section>
  <section id="rita" className="section"><div className="section-heading"><div><Eyebrow>09 // RITA</Eyebrow><h2>Not every connection is a story.</h2></div><p className="section-intro">Relationships are easy to collect. Meaning is harder to see.</p></div><div className="rita-grid"><RitaSequencer /><div className="prose"><p>RITA — the Relationship Intelligence &amp; Triage Analyst layer within ATIS — examines relationships, identifies patterns and helps form coherent stories from underlying evidence.</p><p className="statement">CONNECTION ≠ COHERENCE<br />COHERENCE → STORY</p></div></div></section>
  <section id="perspective" className="section split"><div><Eyebrow>10 // One ecosystem. Different questions.</Eyebrow><h2>The ecosystem stays the same. Your lens changes.</h2></div><div className="prose"><p>An investor may focus on capital, policy, institutions, projects and enterprises. An enterprise may focus on customers, partners, suppliers, infrastructure and regulation. A researcher may focus on evidence, entities, relationships and patterns.</p><p>The underlying ecosystem remains. The perspective changes.</p></div></section>
  <section id="participate" className="section form-section"><div className="center-copy"><Eyebrow>15 // Get involved</Eyebrow><h2>Where do you fit into the question?</h2><p>AKSOS is still exploring the hypothesis. Tell us what brought you here, what you are exploring, and where you see yourself engaging with the work.</p></div><InterestForm contactEmail={process.env.CONTACT_EMAIL ?? 'connect@atis.net'} /></section>
  <section className="section closing"><Eyebrow>AKSOS // The work continues</Eyebrow><h2>Make the invisible <em>legible.</em></h2><p>There is already more happening inside an ecosystem than any one person can see. The question is what becomes possible when more of that structure becomes visible.</p><a className="text-link" href="https://atis.aksos.net" target="_blank" rel="noreferrer">Explore ATIS →</a></section>
  <footer><AKSOSLogo /><span>Exploring ecosystem visibility, intelligence and participation.</span><a href="mailto:connect@atis.net">connect@atis.net</a></footer>
</main> }
