import { ArrowUpRight } from 'lucide-react'
import { AKSOSLogo, ATISLogo } from '@/components/brand'
import { AtisProgression, EcosystemField, FragmentedField, IntellectualHistory, PerspectiveSection, PathwayFlow, ProvenanceChain, RitaSequencer } from '@/components/aksos-graphs'
import { InterestForm } from '@/components/interest-form'

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span className="eyebrow-rule" />{children}</p> }
function Header() { return <header className="site-header"><a href="#top" aria-label="AKSOS home"><AKSOSLogo compact /></a><nav className="nav" aria-label="Primary navigation"><a href="#problem">Problem</a><a href="#atis">ATIS</a><a href="#rita">RITA</a><a href="#participate">Participate</a></nav><a className="header-link" href="#participate">Get involved <ArrowUpRight size={14} /></a></header> }
function Flow({ items }: { items: string[] }) { return <div className="flow">{items.map((item, index) => <span key={item}><b>{item}</b>{index < items.length - 1 && <i>↓</i>}</span>)}</div> }

export default function Page() { return <main id="top"><Header />
  <section className="hero section-grid"><div className="hero-copy"><Eyebrow>AKSOS // ECOSYSTEM VISIBILITY</Eyebrow><h1>Make the invisible <em>legible.</em></h1><p className="lede">Across every economy, people, enterprises, institutions, capital, projects, policies, markets and ideas move around one another. The information exists. What is harder to see is how those things relate.</p><a className="text-link" href="#problem">Explore the work →</a><div className="hero-meta"><span>YOU → AKSOS → INTELLIGENCE → OPPORTUNITY → ACTION</span></div></div><EcosystemField /></section>
  <section id="problem" className="section split"><div><Eyebrow>01 // The visibility problem</Eyebrow><h2>Information is everywhere. Context is harder to find.</h2></div><div className="prose"><p>A government announcement may affect a project. A policy may change an industry. A company may depend on an institution. A report may contain a fact that only becomes meaningful when connected to something else.</p><p>These relationships are scattered across sources, organisations and places. The challenge is understanding what is connected to what, why the connection matters, and what it means from your position.</p><p className="statement">If an ecosystem is difficult to see, it becomes difficult to understand.</p><FragmentedField /></div></section>
  <section className="section split"><div><Eyebrow>02 // The hypothesis</Eyebrow><h2>What if visibility itself is infrastructure?</h2></div><div className="prose"><p>AKSOS began with a hypothesis: if an ecosystem becomes easier to see, it may become easier to understand and participate in. This is not a proven claim. It is a question worth testing.</p><Flow items={['VISIBILITY', 'STRUCTURE', 'UNDERSTANDING', 'PARTICIPATION']} /></div></section>
  <section className="section split"><div><Eyebrow>03 // Origin</Eyebrow><h2>The idea came from trying to understand complex systems.</h2></div><div className="prose"><p>Experience became observation. Observation became a question. The question became a hypothesis worth testing.</p><IntellectualHistory /></div></section>
  <section className="section dark-band"><div className="band-grid"><div><Eyebrow>04 // From idea to experiment</Eyebrow><h2>A hypothesis needs something real to test it against.</h2></div><div className="prose"><p>Zimbabwe is the first environment in which we are exploring the question in practice. Not because one country represents a continent, but because a real ecosystem provides what an abstract model cannot: an opportunity to test the idea against reality.</p><Flow items={['ABSTRACT QUESTION', 'REAL ECOSYSTEM', 'ZIMBABWE', 'TEST', 'OBSERVE', 'LEARN']} /></div></div></section>
  <section id="atis" className="section"><div className="section-heading"><div><Eyebrow>05 // ATIS</Eyebrow><h2><ATISLogo /> Information becoming intelligence.</h2></div><p className="section-intro">ATIS is not simply information → AI → answer. Watch one underlying material gain structure, context and meaning.</p></div><AtisProgression /></section>
  <section className="section split"><div><Eyebrow>06 // Perspective</Eyebrow><h2>The same ecosystem can mean different things to different people.</h2></div><div className="prose"><p>The ecosystem does not change. The question you ask of it does.</p><PerspectiveSection /></div></section>
  <section className="section split"><div><Eyebrow>07 // Provenance</Eyebrow><h2>Intelligence should be inspectable.</h2></div><div className="prose"><p>If a conclusion depends on a relationship, inspect the relationship. If it depends on a fact, inspect the fact. If the fact comes from evidence, identify the source.</p><ProvenanceChain /></div></section>
  <section id="rita" className="section"><div className="section-heading"><div><Eyebrow>08 // RITA</Eyebrow><h2>Not every connection is a story.</h2></div><p className="section-intro">Relationships are easy to collect. Meaning is harder to see.</p></div><div className="rita-grid"><RitaSequencer /><div className="prose"><p>RITA — the Relationship Intelligence &amp; Triage Analyst layer within ATIS — examines relationships, identifies patterns and helps form coherent stories from underlying evidence.</p><p className="statement">CONNECTION ≠ COHERENCE<br />COHERENCE → STORY</p></div></div></section>
  <section className="section split"><div><Eyebrow>09 // Participation</Eyebrow><h2>Participation is a pathway, not a database record.</h2></div><div className="prose"><p>People contribute context, discover the work, choose how deeply to participate, and access ATIS where appropriate.</p><PathwayFlow /></div></section>
  <section id="participate" className="section form-section"><div className="center-copy"><Eyebrow>10 // Get involved</Eyebrow><h2>Where do you fit into the question?</h2><p>AKSOS is still exploring the hypothesis. Tell us what brought you here, what you are exploring, and where you see yourself engaging with the work.</p></div><InterestForm contactEmail={process.env.CONTACT_EMAIL ?? 'connect@atis.net'} /></section>
  <section className="section closing"><Eyebrow>AKSOS // The work continues</Eyebrow><h2>Learning is evidence for the next question.</h2><p>The outcome is not guaranteed scaling. It is learning, evidence and the possibility of transferability.</p><a className="text-link" href="https://atis.aksos.net" target="_blank" rel="noreferrer">Explore ATIS →</a></section>
  <footer><AKSOSLogo /><span>Exploring ecosystem visibility, intelligence and participation.</span><a href="mailto:connect@atis.net">connect@atis.net</a></footer>
</main> }
